name: Tests

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  galpy-tests:
    name: galpy on ${{ matrix.os }}, python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          $CONDA/bin/conda install -c conda-forge gsl galpy astropy pytest
          pip install .
          pytest tests/test_galpy

  gala-tests:
    name: gala on ${{ matrix.os }}, python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          $CONDA/bin/conda install -c conda-forge gala astropy pytest
          pip install .
          pytest tests/test_gala.py

  agama-tests:
    name: agama on ${{ matrix.os }}, python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          $CONDA/bin/conda install -c conda-forge numpy astropy pytest
          cd ../
          git clone https://github.com/GalacticDynamics-Oxford/Agama.git
          cd Agama
          pip install --user --use-pep517 --config-settings="--global-option=--assume-yes" .
          cd ../pidgey
          pip install .
          pytest tests/test_agama.py
