name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  galpy-tests:
    name: galpy on ${{ matrix.os }}, python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - run: |
          conda activate test
          conda install -c conda-forge gsl galpy astropy pytest
          python -m pip install --upgrade pip
          python -m pip install .
          python -m pytest tests/test_galpy.py

  gala-tests:
    name: gala on ${{ matrix.os }}, python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - run: |
          conda activate test
          conda install -c conda-forge gala astropy pytest
          python -m pip install --upgrade pip
          python -m pip install .
          python -m pytest tests/test_gala.py

  agama-tests:
    name: agama on ${{ matrix.os }}, python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - run: |  # using Agama commit 0c5993d in particular - later versions are not supported yet
          conda activate test
          python -m pip install numpy astropy pytest
          git clone https://github.com/GalacticDynamics-Oxford/Agama.git ../Agama
          cd ../Agama
          git checkout 0c5993d
          python setup.py install --user --assume-yes
          cd ../pidgey
          python -m pip install .
          python -m pytest tests/test_agama.py
